#!/bin/sh
set -e
package_name=chromium-browser-tweaks
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/chromium-browser"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/chromium-browser"
;;
esac
exit 0
