#!/bin/sh
set -e
package_name=chromium-browser-tweaks

case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/bin/chromium-browser.orig" --rename "/usr/bin/chromium-browser"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/bin/chromium-browser")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/bin/chromium-browser.orig" --rename "/usr/bin/chromium-browser"
fi
;;
esac
exit 0
